### ISSUE TITLE
can* variables have mixed meaning

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#214]
A variable might be one like `canDress` or `canPose` - which are used by the Dolly to determine what others can do to her; or a variable might be one like `canDressSelf` or `canFly` which are limits on what Dolly herself can do.

These two meanings need to be separated out by name - preferably in the beginning of the name.

This will be an extensive project.

**Comment by emmamei** [comment]
These variables are used to allow or disallow the dolly from doing things:
- canAFK
- canDressSelf
- canFly
- canSit
- canStand

The following variables are used to determine what dolly capabilities the public is allowed (or disallowed):
- canCarry
- canDress
- canPose
- canRepeat

The last one (`canRepeat`)  is troubling in other ways: it doesn't tell at a glance _what_ it is that repeats (or not): we know from experience that it means a repeat _wind_ but that is not readily apparent.

**Comment by emmamei** [comment]
It won't take much and is worth converting `canRepeat` to `canRepeatWind`.

**Comment by emmamei** [comment]
The conversion of `canRepeat` to `canRepeatWind` is done.

**Comment by emmamei** [comment]
Recommend the following changes:
- [ ] `canCarry` becomes `allowCarry`
- [ ] `canDress` becomes `allowDress`
- [ ] `canPose` becomes `allowPose`
- [ ] `canRepeatWind` becomes `allowRepeatWind`

This makes it clear that these all pertain to permissions granted the public, not permissions granted the Dolly.

**Comment by emmamei** [comment]
Changing these requires changing 5-7 files each.

**Comment by emmamei** [comment]
Using `sed -i` actually makes this simple. The variables were changed as noted.
