### ISSUE TITLE
Meta Issue: Menu Issues

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#42]
The menu code as it stands still has a number of issues in it that make it inefficient in particular it is still using too many listens and has secondary scripts which are opening thing own independent listeners for menu responses which is not necessary.  The menu even if they happen to send the llDialog request themselves they can still point replies back to the listener in MenuHandler and listen instead for responses in the form of a link message code 500 with the following data:

Response|userKey

There are however also a number of additional bugs with the menu which would make sense to fix at the same time because much of the code will be rewritten anyway there is a good chance most would be fixed as incidentals but it is preferable to ensure nothing is missed thus this meta issue.

Any issues involving the menu please create as normal but also make sure to directly reference this issue that will link them together so they can all be tracked.  Simply mention #42 somewhere in the issue description and/or a comment on the issue.
- [x] Transform: The handlers in transform need to be rewritten to use the standard core dialog channel.
- [x] Issue #43: Sitting/No Sitting button exists but is not functional
- [x] Issue #44: Type of Doll > Options menu bad handling
- [x] Issue #46: Poses menu dynamic paging feature does not work is caused by off by 1 error in doPoseMenu

**Comment by emmamei** [comment]
This is a good idea for the next version of the Key. We have a huge number of new features already; let's focus on fixing bugs and problems to generate a stable Key for release.

**Comment by silkymesmeriser** [comment]
Yes though this is mostly bug fixes, the listener issue most definitely is going to need to be resolved we are currently still using a maximum of 16 listeners even though the scripts I have worked on close theirs when they are not in use it unfortunately helps little as most of the overuse of them is elsewhere.  Just to remember here the limit for an avatar and all attachments added together is a total of 32 or at least it was the last I was aware of it being changed it used to be 25 but they increased it to one per attach point when they added mutli attach giving a limit of 32 for attached objects.

It seems that the region limit is still primcount/30 per pool also of which there are two one for every rezzed object in the region and one for every attachment giving a limit of 1,000 for a full region (500 each) and 250 for a homestead (125 each).

Part of me suspects given that there are a few good reasons to do this and the fact that some of it does in fact need to be done even to patch up several known bugs that this may be a case where attempting to take the piecemeal approach might actually risk becoming _more_ work than biting the bullet and implementing the whole thing.

Granted issue #45 in particular is a would be nice addition and is none essential to the rest so will probably end up on the back burner at least provided that we don't have to make any significant change to the options or the way they get passed around between scripts at any point, because honestly if we had to make more than minor tweaks to it then it would be quicker to rewrite it in loop form.
