### ISSUE TITLE
Make key scripts portable to other Keys

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#515]
This includes at minimum removing all gem code, or making it more generic. This is related to issue #514 .

**Comment by emmamei** [comment]
The comments from issue https://github.com/emmamei/cdkey/issues/514#issuecomment-715499647 and also from issue https://github.com/emmamei/cdkey/issues/514#issuecomment-715500980 are directly related to this issue. They are relating to making the Key's gem color settings to be generic (so they work on prims prefixed with `Gem` rather than just `Heart`).

This has been done; however, the check is now actually for prims named `Hea` or `Gem` because of speed concerns. Every change in gem color or gem glow or gem light requires a prim scan. This should be eliminated, perhaps with a list of gem-related prim numbers.

**Comment by emmamei** [comment]
To do:
- [x] Confirm operation without gem code
- [x] Put into alternate key
- [x] Wear alternate key for testing period to check operation

**Comment by emmamei** [comment]
The key scripts are working in other keys. Three keys have been set up with CD Key scripts.

Biggest problem is updates - perhaps updating is more important than expected.
